version: '2'
services:
    costosapi-app:
        image: costosapi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://costosapi-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=costosapi
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    costosapi-mongodb:
        extends:
            file: mongodb.yml
            service: costosapi-mongodb
